# 介绍

## 周期函数的复指数形式展开

记:

\begin{equation}
    E_k(x) = e^{ikx}, \quad 0, \pm1, \cdots
\end{equation}

利用 $E_k(x)$ 可以构造复数集上 $L_2[0, 2\pi]$ 空间的标准正交系, 其中 $L_2[0, 2\pi]$上的内积如下定义:

\begin{equation}
    (f, g) = \dfrac{1}{2 \pi}\int\limits_0^{2\pi} f(x)\overline{g(x)}dx
\end{equation}

即意味着:

\begin{equation}
    (E_k, E_m) = 0 \quad k \neq m \quad ; \quad (E_k, E_k) = 1
\end{equation}

对于离散形式, 考虑:

\begin{equation}
    (f, g)_N = \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1}f(x_j)\overline{g(x_j)}
\end{equation}

其中:

\begin{equation}
    x_j = \frac{2 \pi j}{N}, \quad 0 \leq j \leq N-1
\end{equation}


注意, 上述 $(\cdot, \cdot)_N$ 不是内积, 不满足正定性: $(f, f)_N = 0 \Longleftrightarrow f = 0$

$ f $只需要在所有节点上为0 即有 $(f, f)_N = 0$

$\color{green}{引理}$

$\forall N \geq 1:$

\begin{equation}
     (E_k, E_m)_N  =
    \begin{cases}
           1 & N| k-m\\
           0 & otherwise
    \end{cases}
\end{equation}

假设 $f(x)$ 是以 $2 \pi$ 为周期的周期函数, 称 $f(x)$ 为次数不超过 $N-1$ 的指数多项式如果 $f(x)$ 有如下形式:

\begin{equation}
    f(x)  = \sum\limits_{ k = 0}^{N - 1} c_k e^{ik x} = \sum\limits_{k = 0}^{N - 1}c_kE_k(x)
\end{equation}

为了确定$ c_k $, 两边分别利用 $E_m$ 作离散内积得:

\begin{equation}
    (f(x), E_m)_N = \sum\limits_{k = 0}^{N - 1}c_k(E_k, E_m)_N, \quad 0 \leq m \leq N -1 
\end{equation}

将两边展开并且利用上面引理立得:

\begin{equation}
    c_m = \dfrac{1}{N} \sum_{j = 0}^{N - 1}f(x_j)e^{-imx_j}, \quad 0 \leq m \leq N -1
\end{equation}

其中 $ x_j  = \dfrac{2 \pi j }{N}$, 在实际情况下, 通常需要通过 $\left\lbrace f(x_j) \right\rbrace$来确定 $ c_k $ ; 反之, 或者通过  $ c_k $ 来确定 $f(x_j)$, 显然, 直接对上式进行操作, 复杂度将会是 $ O(N^2) .$$Cooley, Tukey$ 提出了计算 $ c_k $的高效算法将计算 $ p(x_j) $的复杂度降低为 $ O(Nlog_2N) $ 这个方法即 $FFT$

## 矩阵形式

经过观察,很容易发现,实际上记 $c = (c_0, c_1, \cdots, c_{N-1})^T $ 并且注意 $e^{ix_j} = \omega_N^j$ 其中: $ \omega_N $表示$ N 次单位根$ 则可以将上面的关系写为矩阵形式如下:

\begin{equation}
    \begin{pmatrix}
        c_0 \\ c_1 \\ c_2 \\ \vdots \\ c_{N-1} 
    \end{pmatrix}
    = \dfrac{1}{N}\begin{pmatrix}
        1 & 1 & 1 & \cdots & 1 \\
        1 & \overline{\omega}_N & \overline{\omega}_N^2 & \cdots & \overline{\omega}_N^{N - 1} \\
        1 & \overline{\omega}_N^2 & \overline{\omega}_N^4 & \cdots & \overline{\omega}_N^{2 \cdot (N - 1)} \\
          &                       &        \cdots         &      \cdots   & \\
        1 & \overline{\omega}_N^{N-1} & \overline{\omega}_N^{2(N - 1)} & \cdots & \overline{\omega}_N^{(N - 1) \cdot (N - 1)} 
    \end{pmatrix}
    \begin{pmatrix}
        f_0 \\ f_1 \\ f_2 \\ \vdots \\ f_{N -1}
    \end{pmatrix}
\end{equation}

其中, $ \omega_N = e^{\frac{2 \pi i}{N}}$,称该由 $f_0, f_1, \cdots , f_{N-1}$求解出$c_0, c_1, \cdots, c_{N-1}$的过程为离散傅里叶变换

\begin{equation}
    \begin{pmatrix}
        f_0 \\ f_1 \\ f_2 \\ \vdots \\ f_{N-1} 
    \end{pmatrix}
    = \begin{pmatrix}
        1 & 1 & 1 & \cdots & 1 \\
        1 & {\omega}_N & {\omega}_N^2 & \cdots & {\omega}_N^{N - 1} \\
        1 & {\omega}_N^2 & {\omega}_N^4 & \cdots & {\omega}_N^{2 \cdot (N - 1)} \\
          &                       &        \cdots         &      \cdots   & \\
        1 & {\omega}_N^{N-1} & {\omega}_N^{2(N - 1)} & \cdots & {\omega}_N^{(N - 1) \cdot (N - 1)} 
    \end{pmatrix}
    \begin{pmatrix}
        c_0 \\ c_1 \\ c_2 \\ \vdots \\ c_{N -1}
    \end{pmatrix}
\end{equation}

$ \omega_N = e^{\frac{2 \pi i}{N}}$,称该由$c_0, c_1, \cdots, c_{N - 1}$ 求出 $f_0, f_1, \cdots, f_{N-1}$的过程为离散傅里叶逆变换

# $FFT$的基本引理

$\color{green}{引理1}$

假设 $p(x), q(x)$ 为 $N-1$ 阶的指数多项式, 并且使得: 对 $ y_j = \frac{\pi j}{N} $成立:

\begin{equation}
    p(y_{2j}) = f(y_{2j}), \quad q(y_{2j}) = f(y_{2j + 1}), \quad 0 \leq j \leq N-1
\end{equation}

则$ f $满足上述条件的阶数小于 $ 2N - 1 $的指数插值多项式存在,并且可以由下式给出:

\begin{equation}
    P(x) = \dfrac{1}{2}(1 + e^{iNx})p(x) + \dfrac{1}{2}(1 - e^{iNx})q(x - \frac{\pi}{N})
\end{equation}

$\color{green}{引理2}$

假设 $\color{green}{引理1}$ 中的多项式 $p(x), q(x), P(x)$ 分别由下式给出:
    
\begin{equation}
    p(x) = \sum\limits_{j = 0}^{N - 1}\alpha_j E_j(x) \quad q(x) = \sum\limits_{j = 0}^{N - 1}\beta_j E_j(x) \quad
    P(x) = \sum\limits_{ j = 0 }^{2N - 1} \gamma_j E_j(x)
\end{equation}

则 $ \forall 0 \leq j \leq N-1:$

\begin{equation}
    \gamma_j = \frac{1}{2}\alpha_j + \frac{1}{2}e^{ \frac{-ij \pi}{N}}\beta_j \quad \gamma_{j + N} = \frac{1}{2}\alpha_j - \frac{1}{2}e^{\frac{-ij \pi}{N}}\beta_j
\end{equation}

# $FFT$ 算法以及时间复杂度

## 直接推导

总结前面, 已经有了如下三个式子:

- 
\begin{align}
    f(x) = \sum\limits_{k = 0}^{N}c_kE_k(x) \\
    c_k = \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1}f(x_j)e^{-ikx_j}
\end{align}

- 假设 p(x), q(x) 为次数等于$N - 1$ 的指数多项式, $ y_j  = \frac{\pi j}{N} $, $ f $ 满足: $ \forall 0 \leq j \leq N - 1$

\begin{equation}
    p(y_{2j}) = f(y_{2j}), \quad q(y_{2j}) = f{（y_{2j + 1}） }
\end{equation}

则存在 f(x) 在节点 $y_j$处 次数不超过 $ 2N - 1$ 的插值多项式$ P(x) $满足:

\begin{equation}
    P(x) = \dfrac{1}{2}(1 + e^{iNx})p(x) + \dfrac{1}{2}(1 - e^{iNx})q(x - \dfrac{\pi}{N})
\end{equation}

- 对上述的 $p(x), q(x), P(x)$ 并且满足:

\begin{equation}
    p(x) = \sum\limits_{j = 0}^{N - 1}\alpha_jE_j(x), \quad  q(x) = \sum\limits_{j = 0}^{N - 1}\beta_jE_j(x), \quad
     P(x) = \sum\limits_{j = 0}^{2N - 1}\gamma_jE_j(x)
\end{equation}

则系数 $ \alpha, \beta, \gamma $有以下关系:

对 $ 0 \leq j \leq N - 1$
\begin{align}
    \gamma_j = \dfrac{1}{2}\alpha_j + \dfrac{1}{2}e^{\frac{-ij\pi}{N}}\beta_j \\ 
    \gamma_{j + N} =  \dfrac{1}{2} \alpha_j - \dfrac{1}{2}e^{\frac{-ij \pi}{N}}\beta_j
\end{align}

现在, 考虑对 $f(x) = \sum\limits_{k = 0}^{2N - 1}c_kE_k(x) $ 

\begin{equation}
    c_k = \dfrac{1}{2N}\sum\limits_{j = 0}^{2N - 1}f(x_j)e^{-ikx_j} \quad x_j = \dfrac{\pi j}{N}
\end{equation}

利用上式, 有:

\begin{equation}
    \begin{cases}
        \gamma_k = \dfrac{1}{2N} \sum\limits_{j = 0}^{2N - 1}f(x_j)e^{-\frac{ikj\pi}{N}} \\
        \alpha_k = \gamma_k + \gamma_{k + N} = \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1} f(x_{2j})e^{-\frac{2ikj\pi}{N}} \quad 0 \leq k \leq N-1  \\
        \beta_k = (\gamma_k - \gamma_{k + N})e^{i \frac{k \pi}{N}} = \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1} f(x_{2j+1})e^{-\frac{2ikj\pi}{N}} \quad 0 \leq k \leq N-1
    \end{cases}
\end{equation}

\begin{equation}
    \begin{cases}
        \alpha_k = \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1} f(x_{2j})e^{-\frac{2ikj\pi}{N}} \\
        \beta_k =  \dfrac{1}{N}\sum\limits_{j = 0}^{N - 1} f(x_{2j+1})e^{-\frac{2ikj\pi}{N}} \\
        \gamma_k = \dfrac{1}{2N} \sum\limits_{j = 0}^{2N - 1}f(x_j)e^{-\frac{ikj\pi}{N}}
    \end{cases}
\end{equation}

## FFT 的矩阵推导

由前面可以看出, 离散傅里叶变换实际上即通过如下矩阵乘法实现 $f_0, f_1, \cdots, f_{N-1}$ 到 $c_0, c_1, \cdots, c_{N-1}$的转换

\begin{equation}
    \begin{pmatrix}
        c_0 \\ c_1 \\ c_2 \\ \vdots \\ c_{N-1} 
    \end{pmatrix}
    = \dfrac{1}{N}\begin{pmatrix}
        1 & 1 & 1 & \cdots & 1 \\
        1 & \overline{\omega}_N & \overline{\omega}_N^2 & \cdots & \overline{\omega}_N^{N - 1} \\
        1 & \overline{\omega}_N^2 & \overline{\omega}_N^4 & \cdots & \overline{\omega}_N^{2 \cdot (N - 1)} \\
          &                       &        \cdots         &      \cdots   & \\
        1 & \overline{\omega}_N^{N-1} & \overline{\omega}_N^{2(N - 1)} & \cdots & \overline{\omega}_N^{(N - 1) \cdot (N - 1)} 
    \end{pmatrix}
    \begin{pmatrix}
        f_0 \\ f_1 \\ f_2 \\ \vdots \\ f_{N -1}
    \end{pmatrix}
\end{equation}

下面将通过四维的例子来在推导快速计算上面矩阵乘法的思路

由:

\begin{equation}
    \begin{pmatrix}
        c_0 \\ c_1 \\ c_2 \\ c_3
    \end{pmatrix}
    = \dfrac{1}{4}
    \begin{pmatrix}
        1 & 1 & 1 & 1 \\
        1 & \overline{\omega}_4 & \overline{\omega}^2_4 & \overline{\omega}^3_4 \\
        1 & \overline{\omega}^2_4 & \overline{\omega}^4_4 & \overline{\omega}^6_4 \\
        1 & \overline{\omega}^3_4 & \overline{\omega}^6_4 & \overline{\omega}^9_4
    \end{pmatrix}
    \begin{pmatrix}
        f_0 \\ f_1 \\ f_2 \\ f_3
    \end{pmatrix}
\end{equation}

下面交换右端矩阵的奇数列和偶数列, 将上述右端改写为如下等价形式:

\begin{equation}
    \begin{pmatrix}
        c_0 \\ c_1 \\ c_2 \\ c_3
    \end{pmatrix}
    = \dfrac{1}{4}
    \begin{pmatrix}
        1 & 1 & 1 & 1 \\
        1 & \overline{\omega}^2_4 & \overline{\omega}_4 & \overline{\omega}^3_4 \\
        1 & \overline{\omega}^4_4 & \overline{\omega}^2_4 & \overline{\omega}^6_4 \\
        1 & \overline{\omega}^6_4 & \overline{\omega}^3_4 & \overline{\omega}^9_4
    \end{pmatrix}
    \begin{pmatrix}
        f_0 \\ f_2 \\ f_1 \\ f_3
    \end{pmatrix}
\end{equation}

记 

\begin{align}
F_4 = \begin{pmatrix}
        1 & 1 & 1 & 1 \\
        1 & \overline{\omega}_4 & \overline{\omega}^2_4 & \overline{\omega}^3_4 \\
        1 & \overline{\omega}^2_4 & \overline{\omega}^4_4 & \overline{\omega}^6_4 \\
        1 & \overline{\omega}^3_4 & \overline{\omega}^6_4 & \overline{\omega}^9_4
    \end{pmatrix}, \quad 
    F_2  = \begin{pmatrix}
        1 & 1\\
        1 & \overline{\omega}_4^2 
    \end{pmatrix} = , \begin{pmatrix}
        1 & 1\\
        1 & \overline{\omega}_2
    \end{pmatrix}\quad
    D_N = \begin{pmatrix}
    1 &   &   &    \\
      & \overline{\omega}_4 & & \\
      &   &  \ddots & \\
      &   &         & \overline{\omega}_4^{N-1}
    \end{pmatrix}
\end{align}

有:

\begin{align}
    F_4f = \begin{pmatrix}
        F_2 & D_2F_2 \\
        F_2 & -D_2F_2
    \end{pmatrix}
    \begin{pmatrix}
        f_{even} \\ f_{odd}
    \end{pmatrix}
\end{align}

从而对于一般的情况 (假设$ N $为偶数), 容易知道, 仍有:

\begin{align}
    F_Nf =
    \begin{pmatrix}
        F_{\frac{N}{2}} & D_{\frac{N}{2}}F_{\frac{N}{2}} \\
        F_{\frac{N}{2}} & -D_{\frac{N}{2}}F_{\frac{N}{2}}
    \end{pmatrix}
    \begin{pmatrix}
        f_{even} \\ f_{odd}
    \end{pmatrix}  
    = \begin{pmatrix}
        I & D_{\frac{N}{2}} \\
        I & -D_{\frac{N}{2}}
    \end{pmatrix}
    \begin{pmatrix}
        F_{\frac{N}{2}}f_{even} \\ F_{\frac{N}{2}}f_{odd}
    \end{pmatrix}
\end{align}

注意, $I$ 和 $D_N$ 均为对角矩阵, 和向量作矩阵乘法每次只需要 $N$ 次的计算量

## 算法时间复杂度

在计算时, 可以通过补 $0$ 的方式将 $ N $ 凑为 2 的幂次方, 从而使得右边能够递归计算下去

上述算法的递归表达式如下:

\begin{equation}
    T(N) = 2T(\frac{N}{2}) + 2N
\end{equation}

从而 $T(N) = Nlog_2N$

可以写为递归树理解如下:

# $FFT$ 的代码实现

## Numpy 模块下的复数运算

为了实现 $FFT$ 需要使用复数操作

In [1]:
import numpy as np

In [2]:
# 创建复数元素数组

a = np.array([1 + 2j, 1 - 3j])
a

array([1.+2.j, 1.-3.j])

In [3]:
print(type(a[0]))

<class 'numpy.complex128'>


In [4]:
# 快速创建复数元素的数组

b = np.zeros(3, dtype = np.complex128)
b

array([0.+0.j, 0.+0.j, 0.+0.j])

In [5]:
# 作用在复数数组上的运算

c = np.sqrt(a)
c

array([1.27201965+0.78615138j, 1.44261527-1.03977826j])

In [6]:
np.sqrt(-1+0j)

1j

In [7]:
w = np.exp(complex(0, np.pi))
w

(-1+1.2246467991473532e-16j)

In [8]:
print(w.real, w.imag)

-1.0 1.2246467991473532e-16


## $FFT$ 的递归实现

In [9]:
def fft_rec(a, lim):
    if lim == 1:
        return a
    w = complex(1, 0)
    wn = complex(np.cos(2 * np.pi / lim), np.sin(2 * np.pi / lim))
    alpha = np.zeros(lim >> 1, dtype = np.complex128)   
    beta = np.zeros(lim >> 1, dtype = np.complex128)   
    for i in range(0, lim >> 1):
        alpha[i] = a[i] + a[i + lim >> 1]
        beta[i] = (a[i] - a[i + lim >> 1]) * wn ** (i)
    fft_rec(alpha, lim >> 2)  # recursion solve
    fft_rec(beta, lim >> 2)
    # merge 
    for k in range(lim >> 2 - 1):
        a[k] = 0.5 * (alpha + wn ** (-k) * beta_k) 
        a[k + lim >> 2] = 0.5 * (alpha - wn ** (-k) * beta_k) 

# $ numpy $下$ FFT $的使用

In [10]:
from numpy import fft